# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lcview.ui'
#
# Created by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(802, 724)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lcWidget = QtGui.QTableWidget(self.centralwidget)
        self.lcWidget.setGeometry(QtCore.QRect(5, 90, 791, 291))
        self.lcWidget.setObjectName(_fromUtf8("lcWidget"))
        self.lcWidget.setColumnCount(0)
        self.lcWidget.setRowCount(0)
        self.loadDictButton = QtGui.QPushButton(self.centralwidget)
        self.loadDictButton.setGeometry(QtCore.QRect(733, 420, 58, 25))
        self.loadDictButton.setObjectName(_fromUtf8("loadDictButton"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(12, 420, 64, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.dnameEdit = DDLineEdit(self.centralwidget)
        self.dnameEdit.setGeometry(QtCore.QRect(80, 420, 649, 24))
        self.dnameEdit.setObjectName(_fromUtf8("dnameEdit"))
        self.dictWidget = QtGui.QTableWidget(self.centralwidget)
        self.dictWidget.setGeometry(QtCore.QRect(10, 450, 781, 71))
        self.dictWidget.setObjectName(_fromUtf8("dictWidget"))
        self.dictWidget.setColumnCount(0)
        self.dictWidget.setRowCount(0)
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 781, 60))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fnameEdit = DDLineEdit(self.layoutWidget)
        self.fnameEdit.setObjectName(_fromUtf8("fnameEdit"))
        self.gridLayout.addWidget(self.fnameEdit, 0, 1, 1, 1)
        self.loadButton = QtGui.QPushButton(self.layoutWidget)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.gridLayout.addWidget(self.loadButton, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cmdEdit = QtGui.QLineEdit(self.layoutWidget)
        self.cmdEdit.setObjectName(_fromUtf8("cmdEdit"))
        self.gridLayout.addWidget(self.cmdEdit, 1, 1, 1, 1)
        self.runButton = QtGui.QPushButton(self.layoutWidget)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.gridLayout.addWidget(self.runButton, 1, 2, 1, 1)
        self.plotButton = QtGui.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(430, 390, 99, 25))
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.plotnewButton = QtGui.QPushButton(self.centralwidget)
        self.plotnewButton.setGeometry(QtCore.QRect(310, 390, 99, 25))
        self.plotnewButton.setObjectName(_fromUtf8("plotnewButton"))
        self.prevPutton = QtGui.QPushButton(self.centralwidget)
        self.prevPutton.setGeometry(QtCore.QRect(10, 390, 113, 27))
        self.prevPutton.setObjectName(_fromUtf8("prevPutton"))
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(680, 390, 113, 27))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.plcButton = QtGui.QPushButton(self.centralwidget)
        self.plcButton.setGeometry(QtCore.QRect(733, 530, 58, 25))
        self.plcButton.setObjectName(_fromUtf8("plcButton"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 530, 81, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.plcnameEdit = DDLineEdit(self.centralwidget)
        self.plcnameEdit.setGeometry(QtCore.QRect(98, 530, 631, 24))
        self.plcnameEdit.setObjectName(_fromUtf8("plcnameEdit"))
        self.blcnameEdit = DDLineEdit(self.centralwidget)
        self.blcnameEdit.setGeometry(QtCore.QRect(100, 560, 631, 24))
        self.blcnameEdit.setObjectName(_fromUtf8("blcnameEdit"))
        self.blcButton = QtGui.QPushButton(self.centralwidget)
        self.blcButton.setGeometry(QtCore.QRect(734, 560, 60, 25))
        self.blcButton.setObjectName(_fromUtf8("blcButton"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(9, 560, 81, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.fitButton = QtGui.QPushButton(self.centralwidget)
        self.fitButton.setGeometry(QtCore.QRect(735, 590, 58, 25))
        self.fitButton.setObjectName(_fromUtf8("fitButton"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 590, 81, 25))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.fitnameEdit = DDLineEdit(self.centralwidget)
        self.fitnameEdit.setGeometry(QtCore.QRect(100, 590, 521, 24))
        self.fitnameEdit.setObjectName(_fromUtf8("fitnameEdit"))
        self.fittypeBox = QtGui.QComboBox(self.centralwidget)
        self.fittypeBox.setGeometry(QtCore.QRect(637, 590, 91, 25))
        self.fittypeBox.setObjectName(_fromUtf8("fittypeBox"))
        self.fittypeBox.addItem(_fromUtf8(""))
        self.fittypeBox.addItem(_fromUtf8(""))
        self.fittypeBox.addItem(_fromUtf8(""))
        self.optionEdit = DDLineEdit(self.centralwidget)
        self.optionEdit.setGeometry(QtCore.QRect(80, 2, 649, 24))
        self.optionEdit.setObjectName(_fromUtf8("optionEdit"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 64, 25))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.optionButton = QtGui.QPushButton(self.centralwidget)
        self.optionButton.setGeometry(QtCore.QRect(730, 0, 58, 25))
        self.optionButton.setObjectName(_fromUtf8("optionButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuConfig = QtGui.QMenu(self.menubar)
        self.menuConfig.setObjectName(_fromUtf8("menuConfig"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAsas = QtGui.QAction(MainWindow)
        self.actionAsas.setObjectName(_fromUtf8("actionAsas"))
        self.actionKepler = QtGui.QAction(MainWindow)
        self.actionKepler.setObjectName(_fromUtf8("actionKepler"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuConfig.addAction(self.actionAsas)
        self.menuConfig.addAction(self.actionKepler)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.label_3.setBuddy(self.dnameEdit)
        self.label.setBuddy(self.fnameEdit)
        self.label_4.setBuddy(self.plcnameEdit)
        self.label_5.setBuddy(self.blcnameEdit)
        self.label_6.setBuddy(self.fitnameEdit)
        self.label_7.setBuddy(self.optionEdit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.loadButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.load_file)
        QtCore.QObject.connect(self.runButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_cmd)
        QtCore.QObject.connect(self.fnameEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.loadButton.click)
        QtCore.QObject.connect(self.cmdEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.runButton.click)
        QtCore.QObject.connect(self.dnameEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.loadDictButton.click)
        QtCore.QObject.connect(self.loadDictButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.load_dict)
        QtCore.QObject.connect(self.lcWidget, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.change_star)
        QtCore.QObject.connect(self.plotButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.plot_lc)
        QtCore.QObject.connect(self.plotnewButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.plot_newlc)
        QtCore.QObject.connect(self.prevPutton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.prev)
        QtCore.QObject.connect(self.nextButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.next)
        QtCore.QObject.connect(self.fnameEdit, QtCore.SIGNAL(_fromUtf8("postDrop()")), MainWindow.load_file)
        QtCore.QObject.connect(self.dnameEdit, QtCore.SIGNAL(_fromUtf8("postDrop()")), MainWindow.load_dict)
        QtCore.QObject.connect(self.fitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.load_fit)
        QtCore.QObject.connect(self.blcButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.load_blc)
        QtCore.QObject.connect(self.plcButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.load_plc)
        QtCore.QObject.connect(self.plcnameEdit, QtCore.SIGNAL(_fromUtf8("postDrop()")), self.plcButton.click)
        QtCore.QObject.connect(self.blcnameEdit, QtCore.SIGNAL(_fromUtf8("postDrop()")), self.blcButton.click)
        QtCore.QObject.connect(self.fitnameEdit, QtCore.SIGNAL(_fromUtf8("postDrop()")), self.fitButton.click)
        QtCore.QObject.connect(self.optionButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.process_options)
        QtCore.QObject.connect(self.optionEdit, QtCore.SIGNAL(_fromUtf8("postDrop()")), MainWindow.process_options)
        QtCore.QObject.connect(self.optionEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.optionButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lightcurve Viewer", None))
        self.lcWidget.setSortingEnabled(True)
        self.loadDictButton.setText(_translate("MainWindow", "Lo&ad", None))
        self.label_3.setText(_translate("MainWindow", "&Dict", None))
        self.label.setText(_translate("MainWindow", "F&ile", None))
        self.loadButton.setText(_translate("MainWindow", "&Load", None))
        self.label_2.setText(_translate("MainWindow", "Command", None))
        self.cmdEdit.setText(_translate("MainWindow", "select * from stars;", None))
        self.runButton.setText(_translate("MainWindow", "&Run", None))
        self.plotButton.setText(_translate("MainWindow", "&Plot", None))
        self.plotnewButton.setText(_translate("MainWindow", "Plot &New", None))
        self.prevPutton.setText(_translate("MainWindow", "&<", None))
        self.nextButton.setText(_translate("MainWindow", "&>", None))
        self.plcButton.setText(_translate("MainWindow", "Load", None))
        self.label_4.setText(_translate("MainWindow", "&phased LC", None))
        self.blcButton.setText(_translate("MainWindow", "Load", None))
        self.label_5.setText(_translate("MainWindow", "&binned LC", None))
        self.fitButton.setText(_translate("MainWindow", "Load", None))
        self.label_6.setText(_translate("MainWindow", "Fi&t", None))
        self.fittypeBox.setItemText(0, _translate("MainWindow", "midpoints", None))
        self.fittypeBox.setItemText(1, _translate("MainWindow", "coeffs", None))
        self.fittypeBox.setItemText(2, _translate("MainWindow", "fullfit", None))
        self.label_7.setText(_translate("MainWindow", "&Options", None))
        self.optionButton.setText(_translate("MainWindow", "Process", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuConfig.setTitle(_translate("MainWindow", "&Config", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAsas.setText(_translate("MainWindow", "&Asas", None))
        self.actionKepler.setText(_translate("MainWindow", "&Kepler", None))

from qutilclasses import DDLineEdit
